<a href="https://colab.research.google.com/github/oscar1234456/Numpy_Practice/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [19]:
my_arr = np.arange(1000000)

In [20]:
my_list = list(range(1000000))

In [21]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 19.4 ms, sys: 43 µs, total: 19.4 ms
Wall time: 25.1 ms


In [22]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 666 ms, sys: 165 ms, total: 831 ms
Wall time: 837 ms


In [24]:
print(my_arr)

[     0      1      2 ... 999997 999998 999999]


In [25]:
data = np.random.randn(2,3)
data

array([[ 0.51853476,  1.30596076, -0.87152964],
       [ 1.73600556,  0.67705422, -1.27547665]])

In [26]:
data = data*2
data

array([[ 1.03706952,  2.61192151, -1.74305928],
       [ 3.47201111,  1.35410845, -2.55095329]])

In [27]:
data+data

array([[ 2.07413904,  5.22384302, -3.48611855],
       [ 6.94402222,  2.7082169 , -5.10190658]])

In [28]:
type(data)

numpy.ndarray

In [32]:
data.shape

(2, 3)

In [33]:
data.dtype

dtype('float64')

In [34]:
data1 = [6, 7.5, 8, 0, 1]

In [37]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [38]:
type(arr1)

numpy.ndarray

In [40]:
data2 = [[0,1,2], [3,4,5]]
arr2 = np.array(data2)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
arr2.ndim

2

In [42]:
arr2.shape

(2, 3)

In [43]:
arr2.dtype

dtype('int64')

In [45]:
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
arr4 = np.zeros((3, 6))
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
arr5 = np.zeros((2, 3, 2))
arr5

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [50]:
arr6 = np.ones((3, 2, 5))
arr6

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [52]:
arr7 = np.empty((5,2))
arr7

array([[4.66175251e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [54]:
arr8 = np.array([1, 2, 3, 4, 5 ])
arr8.dtype

dtype('int64')

In [56]:
float_arr8 = arr8.astype(np.float64)
float_arr8.dtype
float_arr8

array([1., 2., 3., 4., 5.])

In [57]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings.dtype

dtype('<U4')

In [58]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [60]:
int_array = np.arange(10)
# calibers = np.array([.22, .270, .357, .380, .44, .50])
calibers = np.array(["1","2","3"])
int_array.astype(calibers.dtype)

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

In [62]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [64]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [65]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [66]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [67]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [68]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [71]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [72]:
arr = np.array([1,2,3])
arr1 = np.array([2,3,4])
arr*arr1

array([ 2,  6, 12])

In [74]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[5]

5

In [78]:
arr[5:9]

array([5, 6, 7, 8])

In [79]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [81]:
arr2d = np.array([[1,2,3],[3,4,5]])
arr2d

array([[1, 2, 3],
       [3, 4, 5]])

In [83]:
arr2d[1]

array([3, 4, 5])

In [84]:
arr2d[0][2]

3

In [86]:
arr2d[0,1]

2

In [87]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [89]:
arr[2,:]

array([7, 8, 9])

In [90]:
arr[2:, :]

array([[7, 8, 9]])

In [91]:
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [92]:
arr[1,:2]

array([4, 5])

In [94]:
arr[1:2, :2]

array([[4, 5]])

In [95]:
names = np.array(['Bob', 'Joe','Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

In [96]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
data

array([[ 0.60998167, -0.4750541 ,  0.83377753, -1.93518874],
       [-0.16049902, -0.15187762, -0.37197516,  0.14111804],
       [-0.68370928, -0.20785975, -0.22797402,  1.99096022],
       [-0.64430885, -0.54758149,  1.04238802,  0.80648829],
       [-0.95383126, -0.13283719, -0.06306898,  0.52169867],
       [-0.06665623,  0.08206044,  0.30804482, -2.36619322],
       [-0.24388604, -0.7799216 ,  0.66466533,  0.39593256]])

In [99]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [100]:
data[names=='Bob']

array([[ 0.60998167, -0.4750541 ,  0.83377753, -1.93518874],
       [-0.64430885, -0.54758149,  1.04238802,  0.80648829]])

In [101]:
data[names=='Bob', 2:]

array([[ 0.83377753, -1.93518874],
       [ 1.04238802,  0.80648829]])

In [105]:
mask = (names=='Bob')|(names=="Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [106]:
~mask

array([False,  True, False, False, False,  True,  True])

In [112]:
arr = np.empty((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
for i in range(8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [120]:
arr[[4,2,0,5]]

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [121]:
arr[[-1,-2,-3,-4]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.]])

In [122]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [123]:
arr[[1,-2],[2,3]]

array([ 6, 27])

In [125]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [128]:
arr = np.random.randn(6,3)
arr

array([[ 0.71847775,  0.26285484, -1.26553537],
       [ 1.56486367, -0.36669354, -0.57239746],
       [-0.32396078,  0.42142172, -0.23613956],
       [-0.96922448,  0.33607358,  1.36743707],
       [-0.34535039, -0.77819041,  0.8160415 ],
       [ 0.40062679,  0.96034596,  0.35131363]])

In [129]:
np.dot(arr.T, arr)

array([[ 4.289124  , -0.19373621, -3.19491112],
       [-0.19373621,  2.02194322, -0.06036556],
       [-3.19491112, -0.06036556,  4.64420965]])

In [133]:
arr = np.array([1,2])
arr

array([1, 2])

In [134]:
np.dot(arr.T, arr) 

5